baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'WELCOM TO WUJIA'
theme = 'blowfish-main'

[menu]
 [[menu.main]]
  indentifier = "about"
  name = "About"
  url = "/about"
  weight = 10

[menu]
 [[menu.main]]
  indentifier = "posts"
  name = "Posts"
  url = "/posts"
  weight = 20
